apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ohkillsh-apps
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: ohkillsh
  source:
    path: apps
    repoURL: https://github.com/ohkillsh/killsh-devops
    targetRevision: HEAD