apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: nginx:1.25.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
              name: http
